version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: clothed-client-container
    image: clothed-client-image
    ports:
      - "5173:5173"
    networks:
      - clothed-network
networks:
  clothed-network: